### ISSUE TITLE
Lab 2 notes

### ISSUE THREAD

**Issue by AntonC9018** [STANISLAYER/Stanislav-Maximenco-#1]
Форматни код, поменяй extension на .cpp.

https://www.quora.com/What-does-it-mean-to-format-your-code

**Comment by AntonC9018** [comment]
Ну я еще жду вторую часть, до четверга. Пингани меня для просмотра как сделаешь.

**Comment by AntonC9018** [comment]
Вопрос: откуда знаешь термин "экземпляр"? 

https://github.com/STANISLAYER/Stanislav-Maximenco-/blob/14f5004b5d3289f9e7c89efae7cbccc963412c63/lab#L59
Это ясно, но допиши память какой переменной это изменяет по факту. 

https://github.com/STANISLAYER/Stanislav-Maximenco-/blob/14f5004b5d3289f9e7c89efae7cbccc963412c63/lab#L79
Тут тоже напиши, что перезаписывается `s1`.

Формулировка похожа на чью-то, но возможно ошибаюсь. Если списал, в принципе не проблема, главное, чтобы понял как работает, а не тупо перекопировал, потому что это дальше нужно будет понимать.

**Comment by AntonC9018** [comment]
Ответь на гитхабе на мои вопросы пожалуйста.

**Comment by STANISLAYER** [comment]
> Вопрос: откуда знаешь термин "экземпляр"?





 Нашел на одном из форумов, когда гуглил про структуры. Может есть какое-то более корректное слово/определение?

**Comment by STANISLAYER** [comment]
> Вопрос: откуда знаешь термин "экземпляр"?
> 
> https://github.com/STANISLAYER/Stanislav-Maximenco-/blob/14f5004b5d3289f9e7c89efae7cbccc963412c63/lab#L59
> 
> 
> Это ясно, но допиши память какой переменной это изменяет по факту.
> https://github.com/STANISLAYER/Stanislav-Maximenco-/blob/14f5004b5d3289f9e7c89efae7cbccc963412c63/lab#L79
> 
> 
> Тут тоже напиши, что перезаписывается `s1`.
> Формулировка похожа на чью-то, но возможно ошибаюсь. Если списал, в принципе не проблема, главное, чтобы понял как работает, а не тупо перекопировал, потому что это дальше нужно будет понимать.

Я все поменял

**Comment by AntonC9018** [comment]
Откуда знаешь слово экземпляр не ответил

**Comment by AntonC9018** [comment]
>  Нашел на одном из форумов, когда гуглил про структуры. Может есть какое-то более корректное слово/определение?

Не, слово подходит, просто хотел убедиться, что ты его действительно знаешь.

**Comment by STANISLAYER** [comment]
А за эту лабу будет оценка?

**Comment by AntonC9018** [comment]
> А за эту лабу будет оценка?

За лабы идет отдельная семестровая оценка. По какой-то пропорции (не помню точно алгоритм) складывается с оценкой за работу в классе, и с оценками за тесты, получая семестровую по лабе. После этого 60% этой + 40% экзамена дают общую семестровую оценку.

Я не знаю как я буду с оценками пока, наверное на основании этих работ буду ставить. Если ответил на все вопросы и изменил все что я отметил, это максимальный балл, думаю так. Так что тебе переживать тут не за что.
